export const SQUAD_UI = {
  navLabel: "স্কোয়াড",
  title: "English Squad",
  eyebrow: "বন্ধুদের সাথে ইংরেজি শেখো",
  emptyTitle: "তুমি এখনো কোনো Squad-এ নেই",
  emptyBody:
    "নিজের Squad তৈরি করো অথবা বন্ধুদের invite code দিয়ে যোগ দাও। একসাথে XP অর্জন করো আর leaderboard-এ উঠো!",
  createSquad: "Squad তৈরি করো",
  joinSquad: "Squad-এ যোগ দাও",
  weeklyLeaderboard: "সাপ্তাহিক Leaderboard",
  weeklyXp: "সাপ্তাহিক XP",
  lifetimeXp: "লাইফটাইম XP",
  weeklyRank: "সাপ্তাহিক র‍্যাঙ্ক",
  squadLeader: "Squad Leader",
  members: "সদস্য",
  inviteCode: "Invite code",
  copyCode: "কপি করো",
  copied: "কপি হয়েছে!",
  weeklyChampion: "🏆 Weekly Champion",
  activity: "সাম্প্রতিক কার্যক্রম",
  missionLabel: (n: number) => `Mission ${String(n).padStart(2, "0")}`,
  totalXp: "মোট XP",
  yourWeekly: "তোমার সাপ্তাহিক অবদান",
  yourLifetime: "তোমার লাইফটাইম অবদান",
  leaveSquad: "Squad ছেড়ে যাও",
  deleteSquad: "Squad মুছে ফেলো",
  transferLead: "Leadership হস্তান্তর",
  removeMember: "সদস্য সরাও",
  createTitle: "নতুন Squad তৈরি",
  createHint: "একটি ছোট নাম বেছে নাও। বন্ধুরা invite code দিয়ে যোগ দেবে।",
  squadName: "Squad নাম",
  createSubmit: "Squad তৈরি করো",
  joinTitle: "Squad-এ যোগ দাও",
  joinHint: "বন্ধুর দেওয়া ছোট invite code লিখো (যেমন GAM4X2)।",
  joinSubmit: "যোগ দাও",
  leaderboardTitle: "সাপ্তাহিক Squad Leaderboard",
  leaderboardHint: "প্রতি শুক্রবার রাত ১২টায় (বাংলাদেশ সময়) Weekly XP রিসেট হয়।",
  playerPromoTitle: "English Squad-এ যোগ দাও",
  playerPromoBody: "বন্ধুদের নিয়ে XP জমা করো আর leaderboard-এ উঠো!",
  profileSquad: "তোমার Squad",
  noSquadProfile: "এখনো কোনো Squad নেই",
  viewSquad: "Squad দেখো",
  badges: "Squad Badges",
  confirmLeave: "তুমি কি নিশ্চিত যে Squad ছেড়ে যেতে চাও?",
  confirmDelete: "সব সদস্য সরিয়ে Squad মুছে ফেলবে। নিশ্চিত?",
} as const;

export const SQUAD_BADGE_LABELS: Record<string, string> = {
  bronze: "Bronze Squad",
  silver: "Silver Squad",
  gold: "Gold Squad",
  platinum: "Platinum Squad",
  diamond: "Diamond Squad",
  legendary: "Legendary Squad",
};
