import {
  opt,
  word,
  type MissionOneLabPack,
  type MissionOneLabQuest,
} from "@/src/lib/mission-one-lab/types";

/**
 * Mission 01 TEST pack · wow examples, full EN+BN glossary on every word.
 * No he/she/it + verb-s/es. Subjects: I / You / We / They / plurals.
 * Isolated progress key so live lab is untouched.
 */

const QUESTS: readonly MissionOneLabQuest[] = [
  {
    id: "subject",
    label: "Quest 1",
    title: "Subject Finder",
    emoji: "🕵️",
    tone: "from-emerald-500 to-teal-600",
    explainLabel: "Subject কী?",
    definitionBn: "বাক্যে কে বা কারা কাজটি করে, সেটিই Subject বা কর্তা।",
    definitionEn: "Who does the action? That word is the Subject.",
    rule: "কে বা কারা কাজ করছে?",
    exampleBn: "তারা ক্রিকেট খেলে।",
    example: [
      word("They", "তারা", "subject"),
      word("play", "খেলে", "verb"),
      word("cricket", "ক্রিকেট", "object"),
    ],
    rescue: [
      "কাজটি কে করছে, সেটি খুঁজো।",
      "বাক্যের কাজের আগে জিজ্ঞেস করো: কে বা কারা?",
      "Subject সাধারণত ইংরেজি বাক্যের শুরুতে থাকে।",
      "They play cricket. খেলার কাজ They করছে। তাই They = Subject।",
    ],
    questions: [
      {
        id: "s1",
        prompt: "Subject কোনটি?",
        sentence: "I eat biryani.",
        bangla: "আমি বিরিয়ানি খাই।",
        options: [opt("eat", "eat", "খাই"), opt("biryani", "biryani", "বিরিয়ানি"), opt("I", "I", "আমি")],
        answer: "I",
        map: [word("I", "আমি"), word("eat", "খাই"), word("biryani", "বিরিয়ানি")],
        tip: "কে খায়? I · আমি।",
      },
      {
        id: "s2",
        prompt: "কাজটি কারা করছে?",
        sentence: "We drink tea.",
        bangla: "আমরা চা খাই।",
        options: [opt("tea", "tea", "চা"), opt("We", "We", "আমরা"), opt("drink", "drink", "খাই / পান করি")],
        answer: "We",
        map: [word("We", "আমরা"), word("drink", "খাই / পান করি"), word("tea", "চা")],
        tip: "কে চা খায়? We · আমরা।",
      },
      {
        id: "s3",
        prompt: "Subject খুঁজে বের করো।",
        sentence: "You send selfies.",
        bangla: "তুমি সেলফি পাঠাও।",
        options: [opt("selfies", "selfies", "সেলফি"), opt("send", "send", "পাঠাও"), opt("You", "You", "তুমি")],
        answer: "You",
        map: [word("You", "তুমি"), word("send", "পাঠাও"), word("selfies", "সেলফি")],
        tip: "কে পাঠায়? You · তুমি।",
      },
      {
        id: "s4",
        prompt: "শেষ চেক: Subject কোনটি?",
        sentence: "Friends share notes.",
        bangla: "বন্ধুরা নোট শেয়ার করে।",
        options: [opt("notes", "notes", "নোট"), opt("Friends", "Friends", "বন্ধুরা"), opt("share", "share", "শেয়ার করে")],
        answer: "Friends",
        map: [word("Friends", "বন্ধুরা"), word("share", "শেয়ার করে"), word("notes", "নোট")],
        tip: "কারা শেয়ার করে? Friends · বন্ধুরা।",
      },
    ],
  },
  {
    id: "verb",
    label: "Quest 2",
    title: "Action Hunter",
    emoji: "⚡",
    tone: "from-sky-500 to-blue-600",
    explainLabel: "Verb কী?",
    definitionBn: "যে শব্দ কাজ বোঝায়, সেটিই Verb বা ক্রিয়া।",
    definitionEn: "The action word is the Verb.",
    rule: "কী কাজ হচ্ছে?",
    exampleBn: "আমি স্বপ্ন তাড়া করি।",
    example: [
      word("I", "আমি", "subject"),
      word("chase", "তাড়া করি", "verb"),
      word("dreams", "স্বপ্ন", "object"),
    ],
    rescue: [
      "বাক্যে কী কাজ হচ্ছে, সেটি খুঁজো।",
      "খাওয়া, খেলা, খোলা, পাঠানো: এগুলো কাজ।",
      "ইংরেজিতে Verb সাধারণত Subject-এর পরে বসে।",
      "I chase dreams. কাজটি chase। তাই chase = Verb।",
    ],
    questions: [
      {
        id: "v1",
        prompt: "Verb কোনটি?",
        sentence: "They play cricket.",
        bangla: "তারা ক্রিকেট খেলে।",
        options: [opt("cricket", "cricket", "ক্রিকেট"), opt("They", "They", "তারা"), opt("play", "play", "খেলে")],
        answer: "play",
        map: [word("They", "তারা"), word("play", "খেলে"), word("cricket", "ক্রিকেট")],
        tip: "খেলার কাজ = play।",
      },
      {
        id: "v2",
        prompt: "কাজ বোঝানো শব্দটি বেছে নাও।",
        sentence: "I open WhatsApp.",
        bangla: "আমি WhatsApp খুলি।",
        options: [opt("open", "open", "খুলি"), opt("WhatsApp", "WhatsApp", "হোয়াটসঅ্যাপ"), opt("I", "I", "আমি")],
        answer: "open",
        map: [word("I", "আমি"), word("open", "খুলি"), word("WhatsApp", "হোয়াটসঅ্যাপ")],
        tip: "খোলার কাজ = open।",
      },
      {
        id: "v3",
        prompt: "Verb খুঁজে বের করো।",
        sentence: "Kids fly kites.",
        bangla: "শিশুরা ঘুড়ি ওড়ায়।",
        options: [opt("kites", "kites", "ঘুড়ি"), opt("fly", "fly", "ওড়ায়"), opt("Kids", "Kids", "শিশুরা")],
        answer: "fly",
        map: [word("Kids", "শিশুরা"), word("fly", "ওড়ায়"), word("kites", "ঘুড়ি")],
        tip: "ওড়ানোর কাজ = fly।",
      },
      {
        id: "v4",
        prompt: "শেষ চেক: Verb কোনটি?",
        sentence: "You win matches.",
        bangla: "তুমি ম্যাচ জিতো।",
        options: [opt("matches", "matches", "ম্যাচ"), opt("You", "You", "তুমি"), opt("win", "win", "জিতো")],
        answer: "win",
        map: [word("You", "তুমি"), word("win", "জিতো"), word("matches", "ম্যাচ")],
        tip: "জয়ের কাজ = win।",
      },
    ],
  },
  {
    id: "object",
    label: "Quest 3",
    title: "Object Catcher",
    emoji: "🎯",
    tone: "from-amber-500 to-orange-600",
    explainLabel: "Object কী?",
    definitionBn: "কাজটি কী বা কাকে নিয়ে হচ্ছে, সেটিই Object বা কর্ম।",
    definitionEn: "What receives the action? That is the Object.",
    rule: "কী বা কাকে?",
    exampleBn: "আমরা আম্মুকে সাহায্য করি।",
    example: [
      word("We", "আমরা", "subject"),
      word("help", "সাহায্য করি", "verb"),
      word("Ammu", "আম্মু", "object"),
    ],
    rescue: [
      "Verb-এর পরে কী বা কাকে প্রশ্ন করো।",
      "আমরা কাকে সাহায্য করি? Ammu।",
      "ইংরেজিতে Object সাধারণত Verb-এর পরে থাকে।",
      "We help Ammu. help কাকে? Ammu। তাই Object।",
    ],
    questions: [
      {
        id: "o1",
        prompt: "Object কোনটি?",
        sentence: "I need English.",
        bangla: "আমার ইংরেজি দরকার।",
        options: [opt("English", "English", "ইংরেজি"), opt("I", "I", "আমি"), opt("need", "need", "দরকার")],
        answer: "English",
        map: [word("I", "আমি"), word("need", "দরকার"), word("English", "ইংরেজি")],
        tip: "কী দরকার? English · ইংরেজি।",
      },
      {
        id: "o2",
        prompt: "কাজটি কিসের ওপর হচ্ছে?",
        sentence: "They buy mangos.",
        bangla: "তারা আম কেনে।",
        options: [opt("buy", "buy", "কেনে"), opt("mangos", "mangos", "আম"), opt("They", "They", "তারা")],
        answer: "mangos",
        map: [word("They", "তারা"), word("buy", "কেনে"), word("mangos", "আম")],
        tip: "তারা কী কেনে? mangos · আম।",
      },
      {
        id: "o3",
        prompt: "Object খুঁজে বের করো।",
        sentence: "You pick flowers.",
        bangla: "তুমি ফুল তোলো।",
        options: [opt("You", "You", "তুমি"), opt("flowers", "flowers", "ফুল"), opt("pick", "pick", "তোলো")],
        answer: "flowers",
        map: [word("You", "তুমি"), word("pick", "তোলো"), word("flowers", "ফুল")],
        tip: "তুমি কী তোলো? flowers · ফুল।",
      },
      {
        id: "o4",
        prompt: "শেষ চেক: Object কোনটি?",
        sentence: "We love stories.",
        bangla: "আমরা গল্প ভালোবাসি।",
        options: [opt("love", "love", "ভালোবাসি"), opt("We", "We", "আমরা"), opt("stories", "stories", "গল্প")],
        answer: "stories",
        map: [word("We", "আমরা"), word("love", "ভালোবাসি"), word("stories", "গল্প")],
        tip: "আমরা কী ভালোবাসি? stories · গল্প।",
      },
    ],
  },
  {
    id: "mix",
    label: "Mini Boss",
    title: "SVO Power Mix",
    emoji: "👑",
    tone: "from-violet-500 to-purple-700",
    explainLabel: "SVO কী?",
    definitionBn: "এবার Subject, Verb এবং Object একসাথে চিনব।",
    definitionEn: "Find all three sentence parts together.",
    rule: "কে + কী করে + কী বা কাকে",
    exampleBn: "আমরা সমস্যা সমাধান করি।",
    example: [
      word("We", "আমরা", "subject"),
      word("solve", "সমাধান করি", "verb"),
      word("problems", "সমস্যা", "object"),
    ],
    rescue: [
      "প্রথমে কাজটি খুঁজো।",
      "তারপর কে কাজ করছে দেখো।",
      "শেষে কী বা কাকে নিয়ে কাজ হচ্ছে দেখো।",
      "S = কে, V = কী করে, O = কী বা কাকে।",
    ],
    questions: [
      {
        id: "m1",
        prompt: "eat কোন অংশ?",
        sentence: "I eat mangos.",
        bangla: "আমি আম খাই।",
        options: [
          opt("Subject", "Subject", "কর্তা"),
          opt("Object", "Object", "কর্ম"),
          opt("Verb", "Verb", "ক্রিয়া"),
        ],
        answer: "Verb",
        map: [word("I", "আমি"), word("eat", "খাই"), word("mangos", "আম")],
        tip: "eat কাজ বোঝায়। তাই Verb · ক্রিয়া।",
      },
      {
        id: "m2",
        prompt: "They কোন অংশ?",
        sentence: "They bring bags.",
        bangla: "তারা ব্যাগ আনে।",
        options: [
          opt("Verb", "Verb", "ক্রিয়া"),
          opt("Subject", "Subject", "কর্তা"),
          opt("Object", "Object", "কর্ম"),
        ],
        answer: "Subject",
        map: [word("They", "তারা"), word("bring", "আনে"), word("bags", "ব্যাগ")],
        tip: "They কাজ করছে। তাই Subject · কর্তা।",
      },
      {
        id: "m3",
        prompt: "rivers কোন অংশ?",
        sentence: "You cross rivers.",
        bangla: "তুমি নদী পার হও।",
        options: [
          opt("Object", "Object", "কর্ম"),
          opt("Verb", "Verb", "ক্রিয়া"),
          opt("Subject", "Subject", "কর্তা"),
        ],
        answer: "Object",
        map: [word("You", "তুমি"), word("cross", "পার হও"), word("rivers", "নদী")],
        tip: "কী পার হও? rivers · নদী। তাই Object।",
      },
      {
        id: "m4",
        prompt: "notes কোন অংশ?",
        sentence: "Friends share notes.",
        bangla: "বন্ধুরা নোট শেয়ার করে।",
        options: [
          opt("Verb", "Verb", "ক্রিয়া"),
          opt("Object", "Object", "কর্ম"),
          opt("Subject", "Subject", "কর্তা"),
        ],
        answer: "Object",
        map: [word("Friends", "বন্ধুরা"), word("share", "শেয়ার করে"), word("notes", "নোট")],
        tip: "কী শেয়ার করে? notes · নোট।",
      },
    ],
  },
  {
    id: "number",
    label: "Quest 4",
    title: "One or Many?",
    emoji: "🔢",
    tone: "from-pink-500 to-rose-600",
    explainLabel: "Singular / Plural কী?",
    definitionBn: "একজন হলে Singular। একের বেশি হলে Plural।",
    definitionEn: "One = Singular. More than one = Plural.",
    rule: "একজন = Singular · একের বেশি = Plural",
    exampleBn: "আমি চা খাই। · তারা চা খায়।",
    example: [
      word("I", "আমি · একজন", "subject"),
      word("They", "তারা · একের বেশি", "subject"),
    ],
    rescue: [
      "Subject একজন নাকি একের বেশি দেখো।",
      "I মানে আমি, তাই একজন।",
      "We বা They মানে একের বেশি।",
      "ধারণা দুই ভাষাতেই একই।",
    ],
    questions: [
      {
        id: "n1",
        prompt: "We: Singular না Plural?",
        sentence: "We open windows.",
        bangla: "আমরা জানালা খুলি।",
        options: [opt("Singular", "Singular", "একবচন"), opt("Plural", "Plural", "বহুবচন")],
        answer: "Plural",
        map: [word("We", "আমরা"), word("open", "খুলি"), word("windows", "জানালা")],
        tip: "We = আমরা = একের বেশি।",
      },
      {
        id: "n2",
        prompt: "I: Singular না Plural?",
        sentence: "I start games.",
        bangla: "আমি খেলা শুরু করি।",
        options: [opt("Plural", "Plural", "বহুবচন"), opt("Singular", "Singular", "একবচন")],
        answer: "Singular",
        map: [word("I", "আমি"), word("start", "শুরু করি"), word("games", "খেলা")],
        tip: "I = আমি = একজন।",
      },
      {
        id: "n3",
        prompt: "Boys: Singular না Plural?",
        sentence: "Boys play cricket.",
        bangla: "ছেলেরা ক্রিকেট খেলে।",
        options: [opt("Singular", "Singular", "একবচন"), opt("Plural", "Plural", "বহুবচন")],
        answer: "Plural",
        map: [word("Boys", "ছেলেরা"), word("play", "খেলে"), word("cricket", "ক্রিকেট")],
        tip: "Boys = ছেলেরা = একের বেশি।",
      },
      {
        id: "n4",
        prompt: "Players: Singular না Plural?",
        sentence: "Players kick balls.",
        bangla: "খেলোয়াড়রা বল মারে।",
        options: [opt("Plural", "Plural", "বহুবচন"), opt("Singular", "Singular", "একবচন")],
        answer: "Plural",
        map: [word("Players", "খেলোয়াড়রা"), word("kick", "মারে"), word("balls", "বল")],
        tip: "Players = খেলোয়াড়রা = একের বেশি।",
      },
    ],
  },
  {
    id: "person",
    label: "Quest 5",
    title: "Who Is Speaking?",
    emoji: "💬",
    tone: "from-indigo-600 to-violet-700",
    explainLabel: "Person কী?",
    definitionBn:
      "Person মানে কে কথা বলছে। I/We = First Person (উত্তম পুরুষ)। You = Second Person (মধ্যম পুরুষ)। He/She/They = Third Person (প্রথম পুরুষ / অন্য কারো কথা)।",
    definitionEn:
      "Person shows who is speaking. I/We = First. You = Second. He/She/They = Third (talking about someone else).",
    rule: "I/We = First · You = Second · They = Third",
    exampleBn: "আমি বলি · তুমি শোনো · তারা দেখে",
    example: [
      word("I / We", "আমি / আমরা · First", "subject"),
      word("You", "তুমি / তোমরা · Second", "subject"),
      word("They", "তারা · Third", "subject"),
    ],
    rescue: [
      "নিজের কথা বললে First Person।",
      "সামনের মানুষকে বললে Second Person।",
      "অন্যদের কথা বললে Third Person।",
      "I/We = First · You = Second · They = Third।",
    ],
    questions: [
      {
        id: "p1",
        prompt: "I কোন Person?",
        sentence: "I draw maps.",
        bangla: "আমি মানচিত্র আঁকি।",
        options: [
          opt("Second Person", "Second Person", "মধ্যম পুরুষ"),
          opt("First Person", "First Person", "উত্তম পুরুষ"),
          opt("Third Person", "Third Person", "প্রথম পুরুষ"),
        ],
        answer: "First Person",
        map: [word("I", "আমি"), word("draw", "আঁকি"), word("maps", "মানচিত্র")],
        tip: "নিজের কথা I দিয়ে। First Person।",
      },
      {
        id: "p2",
        prompt: "We কোন Person?",
        sentence: "We carry boxes.",
        bangla: "আমরা বাক্স বহন করি।",
        options: [
          opt("Third Person", "Third Person", "প্রথম পুরুষ"),
          opt("Second Person", "Second Person", "মধ্যম পুরুষ"),
          opt("First Person", "First Person", "উত্তম পুরুষ"),
        ],
        answer: "First Person",
        map: [word("We", "আমরা"), word("carry", "বহন করি"), word("boxes", "বাক্স")],
        tip: "We = আমরা = নিজের দল = First Person।",
      },
      {
        id: "p3",
        prompt: "You কোন Person?",
        sentence: "You drink water.",
        bangla: "তুমি পানি পান করো।",
        options: [
          opt("First Person", "First Person", "উত্তম পুরুষ"),
          opt("Third Person", "Third Person", "প্রথম পুরুষ"),
          opt("Second Person", "Second Person", "মধ্যম পুরুষ"),
        ],
        answer: "Second Person",
        map: [word("You", "তুমি"), word("drink", "পান করো"), word("water", "পানি")],
        tip: "যার সঙ্গে কথা বলি = You = Second Person।",
      },
      {
        id: "p4",
        prompt: "They কোন Person?",
        sentence: "They read maps.",
        bangla: "তারা মানচিত্র পড়ে।",
        options: [
          opt("Second Person", "Second Person", "মধ্যম পুরুষ"),
          opt("Third Person", "Third Person", "প্রথম পুরুষ"),
          opt("First Person", "First Person", "উত্তম পুরুষ"),
        ],
        answer: "Third Person",
        map: [word("They", "তারা"), word("read", "পড়ে"), word("maps", "মানচিত্র")],
        tip: "অন্যদের কথা They = Third Person।",
      },
    ],
  },
  {
    id: "order",
    label: "Quest 6",
    title: "Order Detective",
    emoji: "🧩",
    tone: "from-cyan-500 to-sky-700",
    explainLabel: "Word order কী?",
    definitionBn: "বাংলায় সাধারণত S-O-V। ইংরেজিতে S-V-O। অর্থ একই, শুধু জায়গা বদলায়।",
    definitionEn: "English order: Subject + Verb + Object.",
    rule: "English = S + V + O",
    exampleBn: "তারা মাছ ধরে।",
    example: [
      word("They", "তারা", "subject"),
      word("catch", "ধরে", "verb"),
      word("fish", "মাছ", "object"),
    ],
    rescue: [
      "ইংরেজিতে Subject আগে বসাও।",
      "তারপর Verb বসাও।",
      "Object সবশেষে বসাও।",
      "They + catch + fish = They catch fish.",
    ],
    questions: [
      {
        id: "w1",
        mode: "rearrange",
        prompt: "শব্দগুলো ট্যাপ করে SVO বাক্য সাজাও।",
        bangla: "আমি ভাত খাই।",
        options: [],
        answer: "I eat rice",
        correctOrder: ["I", "eat", "rice"],
        tiles: [word("rice", "ভাত"), word("I", "আমি"), word("eat", "খাই")],
        map: [word("I", "আমি"), word("eat", "খাই"), word("rice", "ভাত")],
        tip: "Subject + Verb + Object: I eat rice.",
      },
      {
        id: "w2",
        mode: "rearrange",
        prompt: "শব্দগুলো ট্যাপ করে সঠিক order বানাও।",
        bangla: "আমরা চা খাই।",
        options: [],
        answer: "We drink tea",
        correctOrder: ["We", "drink", "tea"],
        tiles: [word("drink", "খাই"), word("tea", "চা"), word("We", "আমরা")],
        map: [word("We", "আমরা"), word("drink", "খাই"), word("tea", "চা")],
        tip: "We + drink + tea।",
      },
      {
        id: "w3",
        mode: "rearrange",
        prompt: "ক্রিকেট বাক্যটি SVO-তে সাজাও।",
        bangla: "তারা ক্রিকেট খেলে।",
        options: [],
        answer: "They play cricket",
        correctOrder: ["They", "play", "cricket"],
        tiles: [word("cricket", "ক্রিকেট"), word("They", "তারা"), word("play", "খেলে")],
        map: [word("They", "তারা"), word("play", "খেলে"), word("cricket", "ক্রিকেট")],
        tip: "They + play + cricket।",
      },
      {
        id: "w4",
        mode: "rearrange",
        prompt: "শেষ চেক: নোট বাক্যটি সাজাও।",
        bangla: "বন্ধুরা নোট শেয়ার করে।",
        options: [],
        answer: "Friends share notes",
        correctOrder: ["Friends", "share", "notes"],
        tiles: [word("share", "শেয়ার করে"), word("notes", "নোট"), word("Friends", "বন্ধুরা")],
        map: [word("Friends", "বন্ধুরা"), word("share", "শেয়ার করে"), word("notes", "নোট")],
        tip: "Friends + share + notes।",
      },
    ],
  },
  {
    id: "boss",
    label: "Final Boss",
    title: "Bangla to English",
    emoji: "🏆",
    tone: "from-amber-500 to-yellow-600",
    explainLabel: "কীভাবে সাজাবো?",
    definitionBn: "এবার বাংলা দেখে শব্দগুলো ট্যাপ করে ইংরেজি বাক্য সাজাও।",
    definitionEn: "Tap the word chips to build SVO English.",
    rule: "অর্থ একই · Order বদলাবে",
    exampleBn: "আমি বিরিয়ানি খাই।",
    example: [
      word("I", "আমি", "subject"),
      word("eat", "খাই", "verb"),
      word("biryani", "বিরিয়ানি", "object"),
    ],
    rescue: [
      "বাংলা শব্দগুলোর English pair দেখো।",
      "Subject-কে আগে রাখো।",
      "Verb-কে Subject-এর পরে রাখো।",
      "শেষে Object বসিয়ে সম্পূর্ণ SVO বাক্য বানাও।",
    ],
    questions: [
      {
        id: "b1",
        mode: "rearrange",
        prompt: "সঠিক ইংরেজি বাক্য সাজাও।",
        bangla: "আমরা মাছ খাই।",
        options: [],
        answer: "We eat fish",
        correctOrder: ["We", "eat", "fish"],
        tiles: [word("fish", "মাছ"), word("We", "আমরা"), word("eat", "খাই")],
        map: [word("We", "আমরা"), word("eat", "খাই"), word("fish", "মাছ")],
        tip: "We + eat + fish।",
      },
      {
        id: "b2",
        mode: "rearrange",
        prompt: "বই কেনার বাক্যটি সাজাও।",
        bangla: "তারা বই কেনে।",
        options: [],
        answer: "They buy books",
        correctOrder: ["They", "buy", "books"],
        tiles: [word("books", "বই"), word("buy", "কেনে"), word("They", "তারা")],
        map: [word("They", "তারা"), word("buy", "কেনে"), word("books", "বই")],
        tip: "They + buy + books।",
      },
      {
        id: "b3",
        mode: "rearrange",
        prompt: "ঘুড়ির বাক্যটি সাজাও।",
        bangla: "তুমি ঘুড়ি ওড়াও।",
        options: [],
        answer: "You fly kites",
        correctOrder: ["You", "fly", "kites"],
        tiles: [word("fly", "ওড়াও"), word("You", "তুমি"), word("kites", "ঘুড়ি")],
        map: [word("You", "তুমি"), word("fly", "ওড়াও"), word("kites", "ঘুড়ি")],
        tip: "You + fly + kites।",
      },
      {
        id: "b4",
        mode: "rearrange",
        prompt: "Final hit: খেলনার বাক্যটি সাজাও।",
        bangla: "শিশুরা খেলনা ভালোবাসে।",
        options: [],
        answer: "Children love toys",
        correctOrder: ["Children", "love", "toys"],
        tiles: [word("toys", "খেলনা"), word("Children", "শিশুরা"), word("love", "ভালোবাসে")],
        map: [word("Children", "শিশুরা"), word("love", "ভালোবাসে"), word("toys", "খেলনা")],
        tip: "Children + love + toys।",
      },
    ],
  },
];

export const MISSION_ONE_LAB_TEST_PACK: MissionOneLabPack = {
  id: "mission-01-lab-test",
  badge: "Mission 01 Test",
  progressKey: "gamlish:mission-one-lab-test:v2",
  openingEyebrow: "TEST ONLY · Live Mission 01 অপরিবর্তিত",
  openingTitle: "বাক্যের Secret Map · Test",
  openingBody:
    "আগে Mission 01-এর টিচিং ভিডিও দেখো। তারপর practice। Order/Final Boss-এ শব্দ ট্যাপ করে rearrange করো।",
  openingExampleBn: "আমি বিরিয়ানি খাই।",
  openingExample: [
    word("I", "আমি", "subject"),
    word("eat", "খাই", "verb"),
    word("biryani", "বিরিয়ানি", "object"),
  ],
  partCountHint: "Video → 8 parts · tap-to-rearrange bosses · EN+BN every word",
  skillBadges: ["Subject Finder", "Action Hunter", "Object Catcher", "SVO Builder"],
  victoryTitle: "Mission 01 Test জয়!",
  victorySub: "তুমি এখন action বাক্য বানাতে পারো। কিন্তু একটা বড় গ্যাপ এখনো আছে…",
  cliffhangerTitle: "Mission 02 · Talk About Myself",
  cliffhangerBody:
    "তুমি কাজের বাক্য বানাতে পারো। কিন্তু এখনো নিজের পরিচয় বলতে পারো না।",
  cliffhangerTeaser: ["I ___ a student.", "You ___ brave.", "They ___ my friends."],
  unlockClarity:
    "Mission 01 ফ্রি। পেইড আনলক = Mission 02 এবং পুরো Foundations পথ (শুধু ১টা মিশন নয়)।",
  videoUrl: "https://youtu.be/UeD25OfPXew",
  videoTitle: "Learn: Word Order",
  videoSoftLock: true,
  quests: QUESTS,
};
